export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const EMAIL_REGEX_FAILURE = 'EMAIL_REGEX_FAILURE';
export const PASSWORD_FAILURE = 'PASSWORD_FAILURE';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
