export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const SET_FIRST_LOGIN = 'SET_FIRST_LOGIN';
export const REGEX_FAILURE = 'REGEX_FAILURE';
